name: Run Facebook Lead Sync

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  fb-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          FB_EMAIL: ${{ secrets.FB_EMAIL }}
          FB_PASS: ${{ secrets.FB_PASS }}
          SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          GSHEET_CREDENTIALS_JSON: ${{ secrets.GSHEET_CREDENTIALS_JSON }}
        run: python main.py
